### ISSUE TITLE
Import / Export Salt Files

### ISSUE THREAD

**Issue by CyberLizard** [blockstrap/framework#42]
The salt should be a downloadable file either .txt or .json perhaps. Some salts (with security question and other extra information embedded) literally freeze up notepad or crash evernote when pasted due to their length.

**Comment by msmalley** [comment]
@CyberLizard - Presume you agree we should have the choice of both?

Download Wallet / Download Salt

Not easy to generate file from browser using JS only. Have been unable to find a method that works consistently across browsers, not to mention having the worry of mobile. This was why we originally chose to have a copy and paste method instead. Open to further thoughts and suggestions though?

**Comment by CyberLizard** [comment]
I think an option to store the salt to a file at least for a desktop client would be optimal. For the wallets you can already backup the private keys inc the QR which is btw very nicely done.

I understand what you're saying though about the limitations of creating the feature. The "freezing" issue only really occurs on large salts with extensive security options selected. Not sure how to work around this.

**Comment by msmalley** [comment]
@CyberLizard - One way or another, I will figure something out. Am off to Singapore to attend and present at FOSS Asia but have moved this to top of my priorities and will look into it as soon as I get back. This will give @wdl1908 some time to think about it :-)

**Comment by wdl1908** [comment]
Problem solved see pull request.

**Comment by CyberLizard** [comment]
@wdl1908 that didn't take you long. :)

**Comment by wdl1908** [comment]
I cheated coinprism has the ability to save from the browser I just went and peeked at the code and went looking for the plugin to do the same.

**Comment by msmalley** [comment]
@CyberLizard and @wdl1908 - have just merged the changes and added a few of my own so that people can now save either everything or just the essential base information as well as adding timestamps to the exported files. Still need a way to ensure that someone can safely export everything without overloading buffers, but may need to work on that later unless either of you think it is a critical problem that needs to be solved now?

**Comment by msmalley** [comment]
Will also need to test the save file functionality from mobile devices and change UX accordingly, so will not be closing this issue until that has been done too.

**Comment by CyberLizard** [comment]
@msmalley works fine and the export "wallet" option is great. Next challenge would be the ability to import the file in case the device was reset via the dashboard or by clearing the cache.

**Comment by msmalley** [comment]
Good point - my bad - forgot about the import part - will try to squeeze that into 0.5

**Comment by msmalley** [comment]
@CyberLizard - please note that latest master branch now allows for backup files to be imported

Please also note that we found the problem with IE, it was regarding BitcoinJS-Lib and it containing characters not valid for IE localStorage. For now, bitcoinjs-lib is forced to not be stored whilst we work on a better way of checking files prior to storing them...

**Comment by CyberLizard** [comment]
Awesome! We already merged it and pushed it to our platform. Keep up the great work!
