### ISSUE TITLE
500 Error when executing DOGE transaction API

### ISSUE THREAD

**Issue by wdl1908** [blockstrap/framework#44]
https://api.blockstrap.com/v0/doge/address/transactions/D5NgVBSZSWhpzWMmZNwzMwWQxRbavSmZkM

**Comment by AdamGiles** [comment]
Confirmed, a quick fix has been deployed to solve the 500 error, but a known side effect is that the transaction time is returned as 0. Investigating that now.

**Comment by AdamGiles** [comment]
Another fix deployed to provide the missing timestamp.
