### ISSUE TITLE
Issue with transaction notifications

### ISSUE THREAD

**Issue by CyberLizard** [blockstrap/framework#45]
There seems to be an issue with the Blockstrap API returning the correct notification when a new transaction is sent or received. I've noticed this happening a couple of times now and it's easy to re-produce. The latest testing was done with DRK but it's the same for all currencies.

To re-produce:

Send a transaction from your account to someone else
Receive a transaction
Compare notifications

Upon receiving the persons payment the notification pop-up will display the initial "sent" notification instead of the new "received" notification. (It is possible that the account needs to have a few transactions logged before this issue becomes clear.)

At times the notification might even display a transactions which is several days old such as the one in this screenshot http://i.imgur.com/auOJJ7v.jpg. That particular transaction is actually 2 days old and it was a BTC transaction despite having "recieved" a BLK transaction.

There is also an issue with the display order of the recent transactions on the dashboard which (at times) displays the wrong sort order with the most recent transaction showing at the bottom of the list.

**Comment by msmalley** [comment]
@CyberLizard - yes, this involves a series of known issues that were recently discovered and are very close to the top of my to-do list. One problem comes from transactions that do not yet have timestamps, which then makes it VERY difficult to put in the right order on lists and another comes from when we first started developing we used inputs and outputs to create the notifications, but are now using and serving transactions from our API in address histories. Hope to have all this resolved by the end of the week.

**Comment by msmalley** [comment]
This has now been addressed and fixed in master and will be released as part of 0.5

Please note that only exception to the fix now comes from API Providers that do not support TX pagination, but as long as you use the Blockstrap API, it should be fine!
